# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x07\x65xample\"\x18\n\tNestedSix\x12\x0b\n\x03six\x18\x06 \x01(\x05\"q\n\tInnerData\x12\x0b\n\x03one\x18\x01 \x01(\x05\x12\x0b\n\x03two\x18\x02 \x01(\x05\x12\r\n\x05three\x18\x03 \x01(\x05\x12\x0c\n\x04\x66our\x18\x04 \x01(\x05\x12\x0c\n\x04\x66ive\x18\x05 \x01(\x05\x12\x1f\n\x03six\x18\x06 \x01(\x0b\x32\x12.example.NestedSix\":\n\nNestedData\x12\x0b\n\x03one\x18\x01 \x01(\x05\x12\x1f\n\x03two\x18\x02 \x03(\x0b\x32\x12.example.InnerData\"5\n\x04\x44\x61ta\x12\x0b\n\x03one\x18\x01 \x01(\x05\x12 \n\x03two\x18\x02 \x03(\x0b\x32\x13.example.NestedDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NESTEDSIX']._serialized_start=23
  _globals['_NESTEDSIX']._serialized_end=47
  _globals['_INNERDATA']._serialized_start=49
  _globals['_INNERDATA']._serialized_end=162
  _globals['_NESTEDDATA']._serialized_start=164
  _globals['_NESTEDDATA']._serialized_end=222
  _globals['_DATA']._serialized_start=224
  _globals['_DATA']._serialized_end=277
# @@protoc_insertion_point(module_scope)
