# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\"\xc7\x01\n\x08LoginReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x02 \x01(\x05\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\t\x12\x11\n\tcreate_at\x18\x05 \x01(\x03\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x07 \x01(\x05\x12\x13\n\x0b\x63hat_server\x18\x08 \x01(\t\x12\x14\n\x0cvoice_server\x18\t \x01(\x05\x12\x15\n\revent_log_url\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQ']._serialized_start=16
  _globals['_LOGINREQ']._serialized_end=215
# @@protoc_insertion_point(module_scope)
