# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitado.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'zitado.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0czitado.proto\"P\n\x04\x63lan\x12\x0e\n\x06\x63lanid\x18\x01 \x01(\r\x12\x10\n\x08\x63lanname\x18\x02 \x01(\t\x12\x12\n\nguildlevel\x18\x04 \x01(\r\x12\x12\n\nlivemember\x18\x05 \x01(\r\"\x80\x01\n\tadminclan\x12\x0f\n\x07idadmin\x18\x01 \x01(\r\x12\x11\n\tadminname\x18\x03 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\r\x12\x0b\n\x03\x65xp\x18\x07 \x01(\r\x12\x0f\n\x07\x62rpoint\x18\x0f \x01(\r\x12\x0f\n\x07\x63spoint\x18\x1f \x01(\r\x12\x11\n\tlastlogin\x18\x18 \x01(\r\"\x8c\x02\n\x04info\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\r\x12\x0b\n\x03\x45xp\x18\x07 \x01(\r\x12\x0e\n\x06\x62\x61nner\x18\x0b \x01(\r\x12\x0e\n\x06\x61vatar\x18\x0c \x01(\r\x12\r\n\x05likes\x18\x15 \x01(\r\x12\x12\n\nBadgeCount\x18\x12 \x01(\r\x12\x11\n\tlastlogin\x18\x18 \x01(\r\x12\x10\n\x08\x63reateat\x18, \x01(\r\x12\x13\n\x0b\x62rrankpoint\x18# \x01(\r\x12\x13\n\x0b\x62rrankscore\x18\x0f \x01(\r\x12\x13\n\x0b\x63srankpoint\x18\x1e \x01(\r\x12\x13\n\x0b\x63srankscore\x18\x1f \x01(\r\x12\n\n\x02OB\x18\x32 \x01(\t\"\x12\n\x03\x62io\x12\x0b\n\x03\x62io\x18\t \x01(\t\"4\n\x03pet\x12\x0b\n\x03pet\x18\x02 \x01(\t\x12\x0e\n\x06petexp\x18\x04 \x01(\r\x12\x10\n\x08petlevel\x18\x03 \x01(\r\"p\n\x05Users\x12\x17\n\x08\x63laninfo\x18\x06 \x03(\x0b\x32\x05.clan\x12\x18\n\tbasicinfo\x18\x01 \x03(\x0b\x32\x05.info\x12\x1d\n\tclanadmin\x18\x07 \x03(\x0b\x32\n.adminclan\x12\x15\n\x07\x62ioinfo\x18\t \x03(\x0b\x32\x04.biob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zitado_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAN']._serialized_start=16
  _globals['_CLAN']._serialized_end=96
  _globals['_ADMINCLAN']._serialized_start=99
  _globals['_ADMINCLAN']._serialized_end=227
  _globals['_INFO']._serialized_start=230
  _globals['_INFO']._serialized_end=498
  _globals['_BIO']._serialized_start=500
  _globals['_BIO']._serialized_end=518
  _globals['_PET']._serialized_start=520
  _globals['_PET']._serialized_end=572
  _globals['_USERS']._serialized_start=574
  _globals['_USERS']._serialized_end=686
# @@protoc_insertion_point(module_scope)
